<div class="content__inner">
    <h2>Search people</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/search_people"); ?>)</strong> API to access people searching endpoint
    </p>
    <br>
    <h4 class="table-title">Get parameters</h4>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th width="15%">Field</th>
                <th width="25%">Value</th>
                <th width="45%">Remarks</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>query</td>
                <td>Search keywords</td>
                <td>
                    E.g. vTubers
                </td>
            </tr>
            <tr>
                <td>offset</td>
                <td>Last post offset ID</td>
                <td>
                    This is only needed when loading posts of the pagination system.
                </td>
            </tr>
            <tr>
                <td>session_id (Optional)</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>​Total post limit for each request</td>
                <td>
                    Recommended: 20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
            <pre><code class="json">{
        "code": 200,
        "message": "Results found",
        "data":[
            {
                "id": 78,
                "about": "",
                "followers": 0,
                "posts": 0,
                "avatar": "http://cdn.vtubers.me/upload/default/avatar.png",
                "last_active": "29 Sep, 22 11:09 AM",
                "username": "vTubersDotMe",
                "fname": "vTubersDotMe",
                "email": "contact@vtubers.me",
                "verified": "0",
                "name": "vTubersDotMe",
                "url": "http://vtubers.me/vTubersDotMe",
                "is_user": false,
                "is_following": false
            }
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
            <pre><code class="json">{
        "code": 204,
        "message": "No data found",
        "data": []
    }

    {
        "code": 400,
        "message": "The search term is invalid or missing",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>