<div style="font-family: Arial, Helvetica, sans-serif; line-height: 1.4; background: #f6f6f7; padding: 30px;">
    <div style="display: flex; flex-direction: row; justify-content: center; margin-bottom: 20px;">
        <div style="height: 50px;">
            <a href="https://vtubers.me">
                <img style="height: 100%;" src="https://vtubers.me/assets/logowhitetext.png" alt="vTubers Dot Me Logo">
            </a>
        </div>
    </div>
    <div style="display: flex; justify-content: center;  margin-bottom: 20px;">
        <div style="background: #fff; border-radius: 2px; padding: 30px; color: #14171a; min-width: 400px;">
            <h1 style="font-size: 32px; font-weight: 700; padding: 0; margin: 0 0 35px 0; text-transform: uppercase;">
                Waitlist
            </h1>
            <h4 style="font-size: 22px; color: #1ca1f3; padding: 0; margin: 0 0 5px 0;">
                Hello, {email}!
            </h4>
            <p style="color: #42688a; padding: 0; margin: 0 0 20px 0; font-size: 16px;">
                vTubers.Me is releasing on Christmas Day @ 12PM CST, visit https://vtubers.me/ for the countdown till release!
            </p>
        </div>
    </div>
    <p style="font-size: 13px; color: #5b7083;">
        You received this email because you registed for our waitlist. <br> This email will not be used again unless it signs up for our platform, so essentially, you've been automatically unsubscribed.
    </p>
    <p style="font-size: 14px; color: #5b7083; padding: 0; margin: 0;">
        <span>
            <a href="https://vtubers.me/support" style="color: #1b95e0;">- Reach out to our Support Team for any questions</a>
        </span>
    </p>
</div>